<?php declare(strict_types=1);

/*
 * This file is part of Shudd3r/Toolshed package.
 *
 * (c) shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Shudd3r\Toolshed\Tests\Doubles;

use Composer\Util\ProcessExecutor;
use Shudd3r\Toolshed\Filesystem\Virtual\VirtualDirectory as Directory;


class FakeProcessExecutor extends ProcessExecutor
{
    public const EXEC_FILE = <<<'EXE'
        #!/usr/bin/env php
        <?php
        
        /**
         * Proxy PHP file generated by Composer
         *
         * This file includes the referenced bin path (../justinrainbow/json-schema/bin/validate-json)
         * using a stream wrapper to prevent the shebang from being output on PHP<8
         *
         * @generated
         */
        
        namespace Composer;
        
        $GLOBALS['_composer_bin_dir'] = __DIR__;
        $GLOBALS['_composer_autoload_path'] = __DIR__ . '/..'.'/autoload.php';
        
        if (PHP_VERSION_ID < 80000) {
            // more code here...
        }
        
        return include __DIR__ . '/..'.'/foo/tool/bin/foo';
        EXE;

    public const BAT_FILE = <<<'BAT'
        @ECHO OFF
        setlocal DISABLEDELAYEDEXPANSION
        SET BIN_TARGET=%~dp0/composer
        SET COMPOSER_RUNTIME_BIN_DIR=%~dp0
        php "%BIN_TARGET%" %*
        BAT;

    private const VALID_OUTPUT = <<<'CLI'
        Loading composer repositories with package information
        Updating dependencies
        Lock file operations: 28 installs, 0 updates, 0 removals
          - Locking acme/some-package (1.5.0)
          - Locking another/package-name (7.1.3)
          - Locking bar/baz (dev-main)
          - Locking foo/bar-baz (2.13.4)
          - Locking something/else-package (0.14.2-dev)
          - Locking {packageName} ({lockedVersion})
          - Locking vendor/super-tool (v3.1.8)
        2 package suggestions were added by new dependencies, use `composer suggest` to see details.
        No security vulnerability advisories found.
        CLI;

    private const INVALID_OUTPUT = <<<'CLI'
        Loading composer repositories with package information
        Updating dependencies
        Your requirements could not be resolved to an installable set of packages.
        
          Problem 1
            - Root composer.json requires {packageName} ^9.6, found {packageName}[{lockedVersion}] but it does not match the constraint.
        CLI;

    public array $commands = [];

    private int    $errorCode     = 0;
    private string $packageName   = 'test/package';
    private string $lockedVersion = '9.10.11';

    private ?Directory $toolsDir;
    private bool       $isWindows;

    public function __construct(?Directory $toolsDir = null, bool $isWindows = false)
    {
        $this->toolsDir  = $toolsDir;
        $this->isWindows = $isWindows;
        parent::__construct();
    }

    public function presetOutput(int $errorCode, string $packageName, string $lockedVersion): void
    {
        $this->errorCode     = $errorCode;
        $this->packageName   = $packageName;
        $this->lockedVersion = $lockedVersion;
    }

    public function execute($command, &$output = null, ?string $cwd = null): int
    {
        $this->commands[$cwd] = $command;
        $output = $this->output($this->errorCode ? self::INVALID_OUTPUT : self::VALID_OUTPUT);

        $this->createBinaries($cwd);

        return $this->errorCode;
    }

    private function output(string $template): string
    {
        return str_replace(
            ['{packageName}', '{lockedVersion}'],
            [$this->packageName, $this->lockedVersion],
            $template
        );
    }

    private function createBinaries(string $cwd): void
    {
        if (!$this->toolsDir || $this->errorCode) { return; }

        $binDir = $this->toolsDir->subdirectory(basename($cwd) . '/vendor/bin');

        $file = $binDir->file('foo');
        $file->exists() || $file->write(self::EXEC_FILE);

        if (!$this->isWindows) { return; }

        $file = $binDir->file('foo.bat');
        $file->exists() || $file->write(self::BAT_FILE);
    }
}
